### ISSUE TITLE
Schema Form > Should auto-update changes when edited locally and saved

### ISSUE THREAD

**Issue by rockymountainhigh1943** [basaltinc/knapsack#175]
When a pattern's schema form is edited locally and saved, the form should be updated within the Bedrock pattern page.

As it stands now — a user needs to manually kill npm and re-run the start command for changes to be caught.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1126343145187461/1136465770127942)

**Comment by joekarasek** [comment]
This could be done, most easily with nodemon that did the restart of system for you. The read of those schema occurs at initial bootup of the server and is then stored in working memory. There might be a way to update GraphQL with file system watches without restarting the whole thing, but I'm afraid that the data gets into other places and would fall out of sync. @EvanLovely thoughts on this?
