### ISSUE TITLE
Variations Toggle Does Not Function

### ISSUE THREAD

**Issue by marywarrington** [basaltinc/knapsack#210]
**Describe the bug**
In the variations section at the bottom of a given pattern, the toggle for any boolean values does not function.

**To Reproduce**
1. Go to a pattern page which contains a boolean in the schema.
2. Scroll down to Variations.
3. Click the toggle.

**Expected behavior**
The toggle should be clickable, and then apply appropriate variation changes.

**Desktop (please complete the following information):**
 - macOS Mojave
 - Chrome
 - 72

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1126343145187461/1136466123683372)

**Comment by joekarasek** [comment]
A quick pass on this suggests a missing/improper react key for either the forms or the boolean. Clicking the boolean in the variations tab IS toggling, its just toggling the boolean in the form above.
