### ISSUE TITLE
iFrame Links Should be Clickable

### ISSUE THREAD

**Issue by marywarrington** [basaltinc/knapsack#229]
**Describe the bug**
Actions within the iFrame should be clickable without navigating to a new page. 

**To Reproduce**
Navigate to a pattern with a clickable element (e.g. a print button). Click it. 

**Expected behavior**
You should be able to continue to interact with the page as usual.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1126343145187461/1136460264192380)

**Comment by joekarasek** [comment]
@marywarrington Can you confirm that this has been addressed. I was unable to reproduce locally. The only disable that is happening is of page redirects within the iFrame, which is intentional.
