### ISSUE TITLE
Component View > Fullscreen > Styling & Spacing

### ISSUE THREAD

**Issue by rockymountainhigh1943** [basaltinc/knapsack#86]
When viewing a component in fullscreen mode, the layout looks very plain and their are obvious spacing issues.

Give this section some love!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1126343145187461/1136467070858349)

**Comment by joekarasek** [comment]
@rockymountainhigh1943 Is this still relevant? Could you give some more specifics around any remaining spacing issues?
